# Generated by Django 5.1.1 on 2024-10-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivorapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesurvivor',
            name='season',
        ),
    ]
