# Generated by Django 5.1.1 on 2024-10-29 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonlog',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonlog',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
